##ACTORS INDEX
GET http://localhost:3000/actors

##ACTORS CREATE
POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name": "Jen",
  "last_name": "Anniston",
  "known_for": "Friends"
}

###ACTORS SHOW
GET http://localhost:3000/actors/9

###ACTORS UPDATE
PATCH http://localhost:3000/actors/14
Content-Type: application/json

{
  "known_for": "The Morning Show"
}

###ACTORS DESTROY
DELETE http://localhost:3000/actors/13

###MOVIES INDEX
GET http://localhost:3000/movies

###MOVIES CREATE
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Titanic",
  "year": 1997,
  "plot": "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic."
}

###MOVIES SHOW
GET http://localhost:3000/movies/11 

###MOVIES UPDATE
PATCH http://localhost:3000/movies/5
Content-Type: application/json

{
  "title": "Toy Story 2",
  "year": 1999,
  "plot": "When Woody is stolen by a toy collector, Buzz and his friends set out on a rescue mission to save Woody before he becomes a museum toy property with his roundup gang Jessie, Prospector, and Bullseye."
}

# POST http://localhost:3000/actor_query_param
# Content-Type: application/json

# {
#   "id": 8
# }