##ACTORS INDEX
GET http://localhost:3000/actors

##ACTORS CREATE
POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name": "Jen",
  "last_name": "Anniston",
  "known_for": "Friends"
}

###ACTOR SHOW
GET http://localhost:3000/actors/9

###ACTOR UPDATE
PATCH http://localhost:3000/actors/14
Content-Type: application/json

{
  "known_for": "The Morning Show"
}

###ACTOR DESTROY
DELETE http://localhost:3000/actors/13

# GET http://localhost:3000/one_movie

# POST http://localhost:3000/actor_query_param
# Content-Type: application/json

# {
#   "id": 8
# }