# @jwt_Kali = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2NDgyMTg3NTN9.nq_xMJ5vFbf4EdrL8sWGN-S8KTkxmafFeJK3pxgNIC4

# @jwt_Sam = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTEzNDk3NzR9.WQRerAeIPo6ivFbbXOJmYlQLKtHf_qLP5bHuPvuTF2c

# @jwt_Evelyn = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgyMTg4Nzd9.lsJZ3DxePht-9g_8RfllvD_yh0E24NSpzRuJIVLuZak

##ACTORS INDEX
GET http://localhost:3000/actors.json


##ACTORS CREATE
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "Test",
  "last_name": "Smith",
  "known_for": "Toy Story",  
  "gender": "woman",  
  "age": 54,  
  "movie_id": 1 
}

###ACTORS SHOW
GET http://localhost:3000/actors/9.json

###ACTORS UPDATE
PATCH http://localhost:3000/actors/14.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTEzNDk3NzR9.WQRerAeIPo6ivFbbXOJmYlQLKtHf_qLP5bHuPvuTF2c
Content-Type: application/json

{
  "known_for": "Friends and The Morning Show"
}

###ACTORS DESTROY
DELETE http://localhost:3000/actors/15

###MOVIES INDEX
GET http://localhost:3000/movies.json

###MOVIES CREATE
POST http://localhost:3000/movies.json
Content-Type: application/json

{
  "title": "death on the nile",
  "year": 2022,
  "plot": "Test plot",
  "director": "Kenneth Branaugh",
  "english": true
}

###MOVIES SHOW
GET http://localhost:3000/movies/29.json

###MOVIES UPDATE
PATCH http://localhost:3000/movies/29.json
Content-Type: application/json

{
  "year": 456
}

###MOVIES DESTROY
DELETE http://localhost:3000/movies/29

###MOVIE_GENRES CREATE
POST http://localhost:3000/movie_genres
Content-Type: application/json

{
  "genre_id": 1,
  "movie_id": 2
}


### USERS CREATE (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Greg",
  "email": "Greg@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### SESSSIONS CREATE (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "Sam@example.com",
  "password": "password"
}


###USERS DESTROY
DELETE http://localhost:3000/users/9