# @jwt_Kali = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2NDgyMTg3NTN9.nq_xMJ5vFbf4EdrL8sWGN-S8KTkxmafFeJK3pxgNIC4

# @jwt_Sam = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NDgyMTg4NDd9.cqOodL7y5J4_U8Qw6r9LSriOj9sPFUf8aF15gLLRMTM

# @jwt_Evelyn = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgyMTg4Nzd9.lsJZ3DxePht-9g_8RfllvD_yh0E24NSpzRuJIVLuZak

##ACTORS INDEX
GET http://localhost:3000/actors.json

##ACTORS CREATE
POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name": "Test",
  "last_name": "TestSmith",
  "known_for": "TestShow",
  "test": 54
  
}

###ACTORS SHOW
GET http://localhost:3000/actors/9

###ACTORS UPDATE
PATCH http://localhost:3000/actors/14
Content-Type: application/json

{
  "known_for": "Test",
  "gender": "F",
  "age": 3
}

###ACTORS DESTROY
DELETE http://localhost:3000/actors/13

###MOVIES INDEX
GET http://localhost:3000/movies

###MOVIES CREATE
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Test",
  "year": 194,
  "plot": "Test plot for movies create",
  "director": "Test Director"
}

###MOVIES SHOW
GET http://localhost:3000/movies/11 

###MOVIES UPDATE
PATCH http://localhost:3000/movies/4
Content-Type: application/json

{
  "year": 123
}

###MOVIES DESTROY
DELETE http://localhost:3000/movies/12


### USERS CREATE (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Kali",
  "email": "Kali@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### SESSSIONS CREATE (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "Evelyn@example.com",
  "password": "password"
}