# @jwt_Kali = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2NDgyMTg3NTN9.nq_xMJ5vFbf4EdrL8sWGN-S8KTkxmafFeJK3pxgNIC4

# @jwt_Sam = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NDk4NTIwNzR9.qaFiFINIkGxgGATYUgCOF41OPdP_MyDs4wRbuGAjBns

# @jwt_Evelyn = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgyMTg4Nzd9.lsJZ3DxePht-9g_8RfllvD_yh0E24NSpzRuJIVLuZak

##ACTORS INDEX
GET http://localhost:3000/actors.json


##ACTORS CREATE
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "Test",
  "last_name": "Smith",
  "known_for": "Toy Story",  
  "gender": "woman",  
  "age": 54,  
  "movie_id": 1 
}

###ACTORS SHOW
GET http://localhost:3000/actors/9.json

###ACTORS UPDATE
PATCH http://localhost:3000/actors/14.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgyMTg4Nzd9.lsJZ3DxePht-9g_8RfllvD_yh0E24NSpzRuJIVLuZak
Content-Type: application/json

{
  "known_for": "The Morning Show"
}

###ACTORS DESTROY
DELETE http://localhost:3000/actors/15

###MOVIES INDEX
GET http://localhost:3000/movies.json

###MOVIES CREATE
POST http://localhost:3000/movies.json
Content-Type: application/json

{
  "title": "Test2",
  "year": 19999,
  "plot": "Test plot for movies create",
  "director": "Test Director",
  "english": false
}

###MOVIES SHOW
GET http://localhost:3000/movies/11.json

###MOVIES UPDATE
PATCH http://localhost:3000/movies/17.json
Content-Type: application/json

{
  "year": 123
}

###MOVIES DESTROY
DELETE http://localhost:3000/movies/


### USERS CREATE (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Greg",
  "email": "Greg@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### SESSSIONS CREATE (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "Sam@example.com",
  "password": "password"
}

###MOVIE_GENRES CREATE
POST http://localhost:3000/movie_genres
Content-Type: application/json

{
  "genre_id": 1,
  "movie_id": 2
}

###USERS DESTROY
DELETE http://localhost:3000/users/9